[package]
name = "chaos_compute"
version = "0.1.0"
description = "ChaosCompute — Decentralized AI inference market on Solana"
edition = "2021"

[lib]
crate-type = ["cdylib", "lib"]
name = "chaos_compute"

[features]
no-entrypoint = []
no-idl = []
no-log-ix-name = []
cpi = ["no-entrypoint"]
default = []

[dependencies]
anchor-lang = "0.30.1"
anchor-spl = "0.30.1"
switchboard-on-demand = { version = "0.5", features = ["anchor"], optional = true }
